# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('image_path', models.CharField(max_length=5000)),
                ('category', models.CharField(max_length=100)),
                ('amount_left', models.IntegerField()),
            ],
        ),
    ]
