# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='a@a.com', max_length=254),
        ),
    ]
